### ISSUE TITLE
PDF

### ISSUE THREAD

**Issue by jstupak** [Snowmass21-software/MCProd#3]
Switch to more modern pdf set?

**Comment by trtomei** [comment]
Will be hard. Adding to the Pythia cards (as per the CMS tune, for instance):
```
PDF:pSet=LHAPDF6:NNPDF31_nnlo_as_0118
Tune:preferLHAPDF=2
```

i.e., trying to use the LHAPDF from within the MadGraph + Pythia combo crashes the whole thing with:
```
 PYTHIA Info from SLHAinterface::initSLHA: No MODSEL found, keeping internal SUSY switched off
 PYTHIA Warning in SLHAinterface::initSLHA: ignoring MASS entries for id = {1,2,3,4,5,11,12,13,14,15,16,21,22,23,24} (m0 < SLHA:minMassSM)
 PYTHIA Warning in SLHAinterface::initSLHA: ignoring DECAY tables for id = {23,24,1,2,3,4,5,11,12,13,14,15,16,21,22} (m0 < SLHA:minMassSM)
 PYTHIA Warning in SLHAinterface::initSLHA: ignoring empty DECAY tables for id = {6,25} (total width provided but no Branching Ratios)
terminate called after throwing an instance of 'LHAPDF::ReadError'
  what():  Could not find a pdfsets.index file
```

So I guess using LHAPDF is going to be hard... however, it **seems** that a simplified version of that PDF is already available in Pythia, e.g. see here: https://pythia.org/latest-manual/PDFSelection.html
```
option 20 : NNPDF3.1 QCD+LUXQED NNLO alpha_s(M_Z) = 0.118. 
```

More investigation soon.

**Comment by jstupak** [comment]
I tried compiling LHAPDF standalone and it seems to be working: https://github.com/Snowmass21-software/MCProd/commit/b4a29f228abc8ef16924e742f75be1ce3913a309

**Comment by jstupak** [comment]
along with d4d3057dff4099a71af4a38e3f5233a6fdf32abd.

These on both on the `gridpacks` branch.

**Comment by jstupak** [comment]
I think the commits I just pushed to `gridpacks` should be good to go now

**Comment by trtomei** [comment]
I don't think so... when we do "install lhapdf6" within MadGraph, it install another version of LHAPDF (6.3.0) instead of the one we installed previously (as per `install.sh`). Are we sure we are picking the right version?

**Comment by jstupak** [comment]
I think maybe I should have removed  `echo "install lhapdf6" | python ./MG5_aMC_v2_9_7/bin/mg5_aMC` from `install.sh`.  But i'll check.  I had some trouble using LHAPDF installed via madgraph, so I installed it standalone instead

**Comment by jstupak** [comment]
Yea, I tested and everything runs fine without (additionally) installing lhapdf through madgraph:
```
INFO: Using LHAPDF v6.4.0 interface for PDFs 
```

**Comment by jstupak** [comment]
Hello Thiago,
You are right, and I don't think the hard coded paths are necessary.  I was trying to debug something and wanted to rule out an issue with the relative paths, but we can remove this.  I'll create a separate issue so as not to forget
